name: lint-trigger

on:
  workflow_dispatch:
  push:
    paths:
      - "*.ps1"
  pull_request:
    paths:
      - "*.ps1"

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .
          settings: linter-settings.psd1
          recurse: true
          output: results.sarif

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif