name: publish-exe

on:
  workflow_dispatch:

  push:
    paths:
      - "**.ps1"

jobs:
  ps1-to-exe:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Ps2exe
        run:  Install-Module ps2exe -force

      - name: Comple
        run:  Invoke-ps2exe .\main.ps1 .\likes-gay-configurator.exe
      
      - name: Publish
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: likes-gay-configurator.exe
          tag_name: v${{ github.run_number }}
          prerelease: false
          name: v${{ github.run_number }}