name: publish-exe

on:
  workflow_dispatch:

  push:
    paths:
      - "**.ps1"

jobs:
  ps1-to-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ps2exe
        shell: powershell
        run: Install-Module ps2exe -force

      - name: Comple
        shell: powershell
        run: Invoke-ps2exe .\main.ps1 .\likes-gay-config.exe
      
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            likes-gay-config.exe
            edge_redirect.ini